### ISSUE TITLE
Run 'exapmle' - Build: failed - Unresolved reference: Secrets

### ISSUE THREAD

**Issue by larabisch** [twigbit/ident-sdk#23]
I tried to run the example and got these errors:

`> Task :example:compileDebugKotlin FAILED
e: C:\Users\bisch\Documents\AusweisApp\ident-sdk\example\src\main\java\com\twigbit\identsdk\example\IndependentIdentificationActivity.kt: (23, 23): Unresolved reference: Secrets`

`e: C:\Users\bisch\Documents\AusweisApp\ident-sdk\example\src\main\java\com\twigbit\identsdk\example\IndependentIdentificationActivity.kt: (24, 26): Unresolved reference: Secrets`

`e: C:\Users\bisch\Documents\AusweisApp\ident-sdk\example\src\main\java\com\twigbit\identsdk\example\IndependentIdentificationActivity.kt: (95, 34): Object is not abstract and does not implement abstract member public abstract fun onInitilized(): Unit defined in com.twigbit.identsdk.core.IdentificationManager.Callback`

`e: C:\Users\bisch\Documents\AusweisApp\ident-sdk\example\src\main\java\com\twigbit\identsdk\example\MainActivity.kt: (49, 23): Unresolved reference: Secrets`

`e: C:\Users\bisch\Documents\AusweisApp\ident-sdk\example\src\main\java\com\twigbit\identsdk\example\MainActivity.kt: (50, 26): Unresolved reference: Secrets`

What can I do to solve these?

**Comment by bergold** [comment]
You need to create the `Secrets.kt` file in the `example/src/main/java/com/twigbit/identsdk/example` folder. Should look like this:
```kotlin
package com.twigbit.identsdk.example

object Secrets {
    const val CLIENT_ID = "abcdef"
    const val CLIENT_REDIRECT_URL = "https://example.com"
}

```

Thank you for the issue, we should mention that in our Readme.

**Comment by larabisch** [comment]
Thank you :)
